#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Question metadata for React interview prep generator."""

from __future__ import annotations

# (num, slug, title, companies, difficulty, memory_hook, concept, options, pick, script_paras, code_hint, tradeoffs, followups, related)

CLASSIC_QUESTIONS = [
    (1, "virtual-dom-reconciliation", "Explain Virtual DOM and Reconciliation",
     "Meta, Google, Amazon, Microsoft", "Medium",
     "Trigger → render → diff → commit — keys = identity",
     "Rendering pipeline and why React batches updates",
     [("Full DOM replace", "Slow, loses focus"), ("Virtual DOM + diff", "Minimal mutations — default pick"), ("Manual DOM", "Error-prone")],
     "Virtual DOM + fiber reconciliation",
     ["React doesn't touch the real DOM on every setState.", "It produces an element tree and diffs against the previous fiber tree.", "Only changed nodes commit to DOM.", "Keys identify list items — index keys break on reorder.", "Batching groups setStates in event handlers for one commit."],
     "Diagram: state change → reconcile → commit",
     [("Batching", "Automatic in 18+", "Manual flushSync", "Auto"), ("Keys", "Index", "Stable ID", "Stable ID")],
     ["What is fiber?", "Difference vs shadow DOM?", "How does Concurrent mode interrupt work?"],
     "rendering-reconciliation.md"),

    (2, "react-keys-lists", "Why Do Keys Matter in Lists?",
     "Meta, Netflix, Stripe", "Easy",
     "Key = row identity for reconciler",
     "List reconciliation and local state preservation",
     [("Index key", "Breaks on insert/sort"), ("Random key each render", "Full remount"), ("Stable id from data", "Correct")],
     "Stable unique id from domain data",
     ["Keys tell React which item moved vs new.", "Index keys cause wrong component instance reuse.", "Focus and useState inside row jump to wrong item.", "Use item.id from API — never Math.random() in render."],
     "List with draggable rows — wrong keys demo",
     [("Key source", "index", "item.id", "item.id"), ("UUID in render", "Bad", "Server id", "Server id")],
     ["Keys in Fragment lists?", "Can two siblings share key?", "React 19 key prop changes?"],
     "rendering-reconciliation.md"),

    (3, "rerender-triggers", "What Causes a Component to Re-render?",
     "Google, Amazon, Apple", "Easy",
     "State, parent, context — not props alone from stable parent",
     "Re-render triggers and propagation",
     [("Only props change", "Incomplete"), ("State/context/parent re-render", "Complete"), ("Any hook call", "Wrong")],
     "State change, parent re-render, context value change",
     ["Own useState/useReducer update schedules re-render.", "Parent re-render re-renders children unless memoized.", "Context change re-renders all consumers.", "Changing ref.current does NOT re-render.", "Memo skips if props shallow-equal."],
     "Parent state toggle re-renders child",
     [("memo", "Skip equal props", "Always render", "Skip equal props")],
     ["Does useContext always re-render?", "React Compiler auto-memo?"],
     "memory-map-master.md"),

    (4, "controlled-vs-uncontrolled", "Controlled vs Uncontrolled Components",
     "Airbnb, Shopify, Microsoft", "Medium",
     "Controlled = React owns value; uncontrolled = ref reads DOM",
     "Form input ownership model",
     [("Controlled", "value + onChange"), ("Uncontrolled", "defaultValue + ref"), ("Hybrid", "Avoid")],
     "Controlled for validation; uncontrolled for simple file input",
     ["Controlled: single source of truth in state.", "Every keystroke setState — enables instant validation.", "Uncontrolled: ref.current.value on submit — less re-renders.", "React Hook Form often uncontrolled internally with register().", "File inputs typically uncontrolled."],
     "TextInput controlled vs ref read",
     [("Validation timing", "on submit", "per keystroke", "Per keystroke needs controlled")],
     ["Fully controlled file upload?", "Switch controlled mid-flight?"],
     "component-patterns.md"),

    (5, "react-fiber-architecture", "What is React Fiber?",
     "Meta, Google, Discord", "Hard",
     "Fiber = unit of work; enables interruptible rendering",
     "Concurrent React architecture",
     [("Stack reconciler", "Legacy sync"), ("Fiber linked list", "Incremental — pick"), ("Web Worker render", "Not React core")],
     "Fiber enables priority and splitting work",
     ["Fiber is a JS object per component instance.", "Work loop can pause for high-priority updates.", "Enables Suspense, transitions, concurrent features.", "Commit phase still synchronous for DOM consistency."],
     "Priority: typing > chart filter",
     [("Rendering", "Sync only", "Interruptible", "Interruptible")],
     ["Scheduler package role?", "Time slicing explained?"],
     "rendering-reconciliation.md"),

    (6, "usestate-vs-usereducer", "useState vs useReducer — When to Use Which?",
     "Stripe, Uber, LinkedIn", "Medium",
     "Reducer when fields transition together",
     "Local state shape complexity",
     [("useState", "Independent scalars"), ("useReducer", "Related transitions"), ("useRef", "Not for UI state")],
     "useReducer for wizard / state machine",
     ["useState for toggles and single fields.", "useReducer when next state depends on prev across fields.", "Reducer pure function easy to unit test.", "Don't use reducer for everything — ceremony cost."],
     "Checkout wizard step reducer",
     [("Testing", "Hook state", "Pure reducer", "Pure reducer")],
     ["useReducer + Context as mini-Redux?", "Immer with reducer?"],
     "state-management.md"),

    (7, "context-performance", "Context API Performance Problem",
     "Meta, Pinterest, Slack", "Hard",
     "All consumers re-render on any value change",
     "Context scaling and mitigation",
     [("One giant context", "Bad"), ("Split contexts", "Better"), ("Zustand selector", "High churn")],
     "Split by update frequency + memo value",
     ["New object in Provider value → all consumers re-render.", "Split Theme vs Session contexts.", "Memoize value tuple.", "For high frequency use external store with selectors.", "Don't put entire app state in Context."],
     "ThemeContext vs CartContext split",
     [("Store", "Context only", "Zustand selectors", "Selectors at scale")],
     ["context-selector pattern?", "Pass dispatch-only context?"],
     "state-management.md"),

    (8, "prop-drilling-solutions", "Prop Drilling — Solutions",
     "Amazon, Walmart, Target", "Medium",
     "Compose; Context; colocate; store — in that order of escalation",
     "Cross-component data passing",
     [("Prop drilling 2 levels", "OK"), ("Context", "Wide low-churn"), ("Zustand", "Many consumers high-churn")],
     "Props first; Context for theme/auth; store if needed",
     ["Don't reach for Context on first drill.", "Component composition can flatten tree — children as props.", "Context for stable globals.", "Document drill vs context decision in design review."],
     "Layout passes user vs UserContext",
     [("Redux", "All drilling", "Minimal global", "Minimal global")],
     ["Component slots vs render props?", "When is drilling actually fine?"],
     "component-patterns.md"),

    (9, "lifting-state-up", "Lifting State Up",
     "Google, Microsoft, Meta", "Easy",
     "Siblings share state at common parent",
     "State colocation vs lift",
     [("Duplicate state in siblings", "Bug"), ("Lift to parent", "Correct"), ("Global immediately", "Overkill")],
     "Lift to nearest common ancestor",
     ["Two components need same value → parent owns state.", "Pass callbacks down to update.", "Lift only as high as needed — not always to App.", "Pair with colocate principle."],
     "Temperature converter two inputs",
     [("State location", "Child", "Parent", "Parent")],
     ["Lift vs Context threshold?", "Colocate first rule?"],
     "state-management.md"),

    (10, "useeffect-dependencies-stale-closure", "useEffect Dependencies & Stale Closures",
     "Meta, Stripe, Coinbase", "Hard",
     "Effect closes over render — deps must be exhaustive",
     "Effect correctness",
     [("Empty deps always", "Stale bug"), ("Exhaustive deps", "Correct"), ("Disable eslint", "Bad")],
     "Exhaustive deps + cleanup + abort",
     ["Missing dep → stale count in interval.", "Functional updates reduce dep needs for setState.", "AbortController in cleanup for fetch.", "Don't lie to eslint-deps — fix root cause.", "Derived state doesn't belong in effect."],
     "Interval logging stale count fix",
     [("Fetch", "No abort", "AbortController", "Abort")],
     ["useEffectEvent?", "When is empty deps OK?"],
     "hooks-deep-dive.md"),

    (11, "custom-hooks-design", "Design a Custom Hook",
     "Vercel, Shopify, Notion", "Medium",
     "Extract stateful logic; prefix use; compose hooks",
     "Custom hook architecture",
     [("Hook returns JSX", "Anti-pattern"), ("Hook returns data + actions", "Good"), ("Class HOC", "Legacy")],
     "Logic-only hook + presentational component",
     ["Name useX — calls other hooks.", "Return stable API: { data, isLoading, mutate }.", "useDebounce, useLocalStorage, useMediaQuery examples.", "Test with renderHook.", "Share between containers without HOC."],
     "useDebouncedValue implementation",
     [("Testing", "Mount full tree", "renderHook", "renderHook")],
     ["Hook calling hook rules?", "Split useAuth vs useAuthProvider?"],
     "hooks-deep-dive.md"),

    (12, "useeffect-vs-uselayouteffect", "useEffect vs useLayoutEffect",
     "Apple, Adobe, Figma", "Medium",
     "Layout = before paint; effect = after paint",
     "Effect timing",
     [("useEffect", "Most side effects"), ("useLayoutEffect", "Measure DOM"), ("useInsertionEffect", "CSS-in-JS lib")],
     "useLayoutEffect only for measure/sync layout",
     ["useLayoutEffect blocks paint — user-visible delay if slow.", "Use for tooltip position measure.", "Default useEffect for fetch/subscribe.", "SSR: useLayoutEffect warns — useEffect or client-only."],
     "Tooltip position measure",
     [("Fetch", "useLayoutEffect", "useEffect", "useEffect")],
     ["Flash of wrong layout?", "SSR hydration mismatch?"],
     "hooks-deep-dive.md"),

    (13, "useref-usecases", "useRef Use Cases",
     "Google, Amazon, Unity", "Easy",
     "Mutable box; DOM access; no re-render on .current change",
     "Refs vs state",
     [("Store UI value in ref", "Wrong for render"), ("DOM focus", "Correct"), ("Previous value pattern", "Correct")],
     "DOM, timers, mutable latest value without render",
     ["ref.current change doesn't trigger re-render.", "Forward ref to child input.", "Store AbortController, interval id.", "Don't read ref during render for UI — use state."],
     "Focus input on modal open",
     [("Previous props", "useState", "useRef", "useRef")],
     ["callback refs?", "ref object vs function ref?"],
     "hooks-deep-dive.md"),

    (14, "react-memo-usememo-usecallback", "React.memo, useMemo, useCallback",
     "Meta, Netflix, Bloomberg", "Hard",
     "Profile first; memo needs stable props",
     "Memoization strategy",
     [("Memo everything", "Waste"), ("Profile then memo", "Senior"), ("Never memo", "Naive at scale")],
     "Profiler-driven memo + stable deps",
     ["memo prevents re-render if props shallow equal.", "useMemo caches computation.", "useCallback stabilizes function reference.", "Inline objects break memo children.", "React Compiler may auto-memo in future."],
     "Expensive list row memo",
     [("useCallback", "Every handler", "Only for memo child", "Targeted")],
     ["React Compiler impact?", "useMemo for referential equality?"],
     "performance-optimization.md"),

    (15, "compound-components-pattern", "Compound Components Pattern",
     "Radix, Shopify Polaris, Atlassian", "Hard",
     "Implicit shared state via Context inside compound API",
     "Flexible component API design",
     [("20 props on Select", "Prop explosion"), ("Compound Select.*", "Composable"), ("Single mega component", "Inflexible")],
     "Compound + internal context",
     ["Select, SelectTrigger, SelectContent share context.", "Consumer controls structure and styling.", "Used in Radix, Reach UI patterns.", "Alternative: headless hook + UI separate."],
     "Tabs compound API sketch",
     [("API", "Config object", "Compound children", "Compound")],
     ["Headless UI vs compound?", "Expose context hook?"],
     "component-patterns.md"),

    (16, "error-boundaries-when-how", "Error Boundaries — When and How",
     "Sentry, Datadog, Airbnb", "Medium",
     "class component; catches render errors in children",
     "Error isolation",
     [("try/catch in render", "Doesn't work"), ("Error boundary", "Catches render"), ("Error in event handler", "Handler try/catch")],
     "Boundary per route/feature + fallback UI",
     ["getDerivedStateFromError + componentDidCatch.", "Doesn't catch event handlers, async, SSR alone.", "Log to Sentry in didCatch.", "Reset boundary with key prop on retry.", "react-error-boundary package wrapper."],
     "FeaturePanel ErrorBoundary fallback",
     [("Granularity", "Whole app", "Per feature", "Per feature")],
     ["React 19 error boundaries?", "Async server component errors?"],
     "component-patterns.md"),

    (17, "portal-modal-focus-trap", "Portals, Modals, and Focus Trap",
     "Stripe, LinkedIn, Discord", "Medium",
     "createPortal escapes z-index; trap focus for a11y",
     "Modal accessibility",
     [("Modal in tree", "Stacking issues"), ("Portal to body", "Correct"), ("No focus trap", "a11y fail")],
     "Portal + focus trap + Esc close",
     ["ReactDOM.createPortal for overlay.", "Focus first focusable on open.", "Restore focus on close.", "aria-modal role dialog.", "Use Radix Dialog or FocusTrap lib."],
     "Modal open focus return",
     [("Library", "Roll own", "Radix Dialog", "Radix")],
     ["Scroll lock body?", "Nested modals?"],
     "component-patterns.md"),

    (18, "hoc-vs-custom-hooks", "HOC vs Custom Hooks",
     "Meta, Twitter, Reddit", "Medium",
     "Hooks replace most HOCs for logic sharing",
     "Code reuse patterns",
     [("HOC withAuth", "Wrapper hell"), ("useAuth hook", "Preferred"), ("Render props", "Legacy")],
     "Custom hooks for logic; HOC rare for cross-cutting",
     ["HOC adds wrapper nodes and prop collision.", "Hooks compose in one component.", "HOC still ok for truly cross-cutting analytics wrapper.", "displayName for HOC debug."],
     "useAuth vs withAuth",
     [("Reuse", "HOC default", "Hook default", "Hook")],
     ["Hooks in class components?", "Multiple hooks vs one HOC?"],
     "component-patterns.md"),

    (19, "react-suspense-lazy", "React.lazy and Suspense",
     "Google, YouTube, Netflix", "Medium",
     "Code split routes; Suspense shows fallback",
     "Lazy loading",
     [("Static import all", "Large bundle"), ("React.lazy + Suspense", "Route split"), ("Dynamic import manual", "More boilerplate")],
     "lazy per route + Suspense fallback",
     ["lazy(() => import('./Page')) returns component.", "Suspense boundary required.", "Nested Suspense for granular loading.", "Error boundary sibling for chunk fail.", "Next.js dynamic() similar."],
     "Route lazy Dashboard",
     [("Fallback", "null", "Skeleton", "Skeleton")],
     ["Suspense for data?", "SSR lazy hydration?"],
     "performance-optimization.md"),

    (20, "virtualize-long-list", "Virtualize a Long List",
     "Bloomberg, Robinhood, Meta", "Hard",
     "Only render visible rows — react-window / tanstack virtual",
     "List performance",
     [("map 10k items", "DOM explosion"), ("Pagination", "OK UX tradeoff"), ("Virtualization", "Best for feeds")],
     "TanStack Virtual or react-window",
     ["Window scroll container with overscan.", "Fixed row height simplifies.", "Variable height needs measure.", "Preserve scroll anchor on prepend.", "Chat apps virtualize message list."],
     "VirtualizedMessageList",
     [("Library", "Manual", "TanStack Virtual", "TanStack Virtual")],
     ["Reverse scroll chat?", "Grid virtualization?"],
     "performance-optimization.md"),

    (21, "tanstack-query-vs-useeffect", "TanStack Query vs useEffect Fetch",
     "Stripe, Vercel, Supabase", "Hard",
     "Server state → Query; not useState cache",
     "Data fetching architecture",
     [("useEffect fetch", "No cache dedupe"), ("TanStack Query", "Cache + retry"), ("Redux for API", "Boilerplate")],
     "TanStack Query default for server data",
     ["Query key identifies cache entry.", "staleTime controls refetch.", "Mutations invalidate.", "Dedupes parallel same-key requests.", "useEffect lacks retry/backoff/stale-while-revalidate."],
     "useQuery users list",
     [("Cache", "useState", "QueryClient", "QueryClient")],
     ["Prefetch on hover?", "SSR dehydrate?"],
     "data-fetching-caching.md"),

    (22, "optimistic-updates-mutation", "Optimistic Updates with Mutations",
     "Twitter, Linear, Notion", "Hard",
     "onMutate snapshot; rollback onError",
     "UX for instant feedback",
     [("Wait for server", "Slow UX"), ("Optimistic UI", "Instant"), ("Pessimistic only", "Safe but sluggish")],
     "Optimistic with rollback",
     ["onMutate cancel outgoing queries.", "Snapshot previous cache.", "Apply optimistic patch.", "onError restore snapshot.", "onSettled invalidate."],
     "Like button optimistic",
     [("Conflict", "Last write wins", "Server reconcile", "Server reconcile")],
     ["Offline queue?", "Idempotency keys?"],
     "data-fetching-caching.md"),

    (23, "infinite-scroll-pagination", "Infinite Scroll vs Pagination",
     "Instagram, Pinterest, Amazon", "Medium",
     "useInfiniteQuery + IntersectionObserver",
     "Large list data loading",
     [("Load all", "Bad"), ("Page buttons", "SEO friendly"), ("Infinite scroll", "Feed UX")],
     "Infinite for feeds; pages for admin tables",
     ["IntersectionObserver sentinel at bottom.", "fetchNextPage when visible.", "getNextPageParam from API cursor.", "Virtualize combined with infinite.", "Accessibility: load more button alternative."],
     "useInfiniteQuery posts",
     [("UX", "Infinite only", "Button fallback", "Button fallback a11y")],
     ["Bidirectional infinite?", "Cursor vs offset?"],
     "data-fetching-caching.md"),

    (24, "websocket-vs-polling-react", "WebSocket vs Polling in React",
     "Slack, Discord, Robinhood", "Medium",
     "WebSocket for push; polling when simple",
     "Real-time UI",
     [("Polling", "Simple, wasteful"), ("WebSocket", "Low latency push"), ("SSE", "One-way server push")],
     "WebSocket for chat; SSE for notifications",
     ["useEffect subscribe + cleanup close socket.", "Reconnect with exponential backoff.", "Update Query cache on message event.", "Don't store socket in useState."],
     "useEffect WebSocket cleanup",
     [("State", "Global socket in module", "Hook with cleanup", "Hook")],
     ["Socket.io vs raw WS?", "Share socket across tabs?"],
     "data-fetching-caching.md"),

    (25, "forms-react-hook-form-zod", "Forms with React Hook Form + Zod",
     "Stripe, Typeform, HubSpot", "Medium",
     "RHF uncontrolled perf + Zod schema validation",
     "Form architecture",
     [("Controlled every field", "Re-render heavy"), ("RHF register", "Performant"), ("Formik", "Valid alternative")],
     "RHF + zodResolver",
     ["Schema single source of validation rules.", "handleSubmit wraps async API.", "Field errors from formState.", "watch() for dependent fields.", "Reset on success."],
     "Login form zod schema",
     [("Validation", "Manual", "Zod schema", "Zod")],
     ["Multi-step wizard?", "Server-side errors map to fields?"],
     "memory-map-master.md"),

    (26, "prevent-double-form-submit", "Prevent Double Form Submit",
     "PayPal, Checkout.com, Amazon", "Easy",
     "Disable button + isPending mutation state",
     "Form reliability",
     [("Double click", "Duplicate orders"), ("Disabled while pending", "Correct"), ("Debounced submit only", "Insufficient")],
     "isSubmitting guard + disable UI",
     ["Set submitting true on submit start.", "Disable button and show spinner.", "useMutation isPending.", "Idempotency key on API for payments."],
     "Submit button isLoading",
     [("API", "Hope for best", "Idempotency-Key header", "Idempotency-Key")],
     ["Optimistic duplicate risk?", "Race two tabs?"],
     "memory-map-master.md"),

    (27, "react-router-data-loaders", "React Router Data Loading",
     "Remix, Shopify, Netflix", "Medium",
     "Loaders defer data before render; errorElement",
     "Routing + data",
     [("fetch in useEffect on mount", "Waterfall"), ("Route loader", "Parallel prefetch"), ("Next.js server", "Framework specific")],
     "Loader + defer + Await for React Router 6.4+",
     ["loader runs before route renders.", "defer for non-critical data.", "errorElement for route errors.", "useLoaderData typed return."],
     "Route loader user profile",
     [("Framework", "CRA only", "Router/Next loaders", "Loader pattern")],
     ["Loader vs TanStack Query?", "Client vs server loader?"],
     "memory-map-master.md"),

    (28, "nextjs-app-router-rsc", "Next.js App Router & Server Components",
     "Vercel, OpenAI, Linear", "Hard",
     "RSC on server; 'use client' for interactivity",
     "Modern React SSR architecture",
     [("All client components", "Large JS"), ("RSC default + client islands", "Optimal"), ("Pages router only", "Legacy")],
     "Server Components default; client for hooks/state",
     ["Server Components: no useState/useEffect.", "Fetch on server close to data.", "Pass serializable props to client.", "use client boundary for event handlers.", "Streaming HTML with Suspense."],
     "Page server fetch + ClientButton",
     [("Data", "Client fetch", "Server fetch", "Server")],
     ["When must use client?", "Caching fetch in RSC?"],
     "memory-map-master.md"),

    (29, "testing-library-best-practices", "React Testing Library Best Practices",
     "GitHub, GitLab, Atlassian", "Medium",
     "Query by role/label; test behavior not implementation",
     "Testing philosophy",
     [("Enzyme shallow", "Implementation detail"), ("RTL user-centric", "Preferred"), ("Snapshot only", "Brittle")],
     "RTL + userEvent + MSW",
     ["getByRole button name submit.", "await userEvent.click.", "MSW mocks API.", "renderHook for custom hooks.", "Avoid testing internal state directly."],
     "Login flow RTL test",
     [("Mock", "Fetch global", "MSW", "MSW")],
     ["Testing async stream?", "E2E vs unit split?"],
     "memory-map-master.md"),

    (30, "mock-service-worker-react", "MSW for API Mocking in Tests",
     "Stripe, Mock Service Worker team", "Medium",
     "Network-level mock — same tests dev and CI",
     "API test doubles",
     [("jest.mock fetch", "Brittle"), ("MSW handlers", "Realistic"), ("Hard-coded in component", "Bad")],
     "MSW server in test setup",
     ["rest.get('/api/user') handler.", "Shared handlers with Storybook.", "Error scenario handlers.", "Reset handlers after each test."],
     "MSW handler 500 error test",
     [("Scope", "Unit only", "Unit + Storybook", "Shared handlers")],
     ["GraphQL MSW?", "Delay simulation?"],
     "memory-map-master.md"),

    (31, "typescript-discriminated-unions-ui", "TypeScript Discriminated Unions for UI State",
     "Linear, Notion, Figma", "Hard",
     "status: loading | error | success narrows type",
     "Type-safe UI states",
     [("boolean flags isLoading isError", "Impossible states"), ("Discriminated union", "Exhaustive switch"), ("any", "Avoid")],
     "Union on status field",
     ["type State = {status:'loading'} | {status:'error',message:string} | {status:'success',data:T}.", "switch(status) exhaustiveness.", "No data access when loading without check.", "Use with TanStack Query status too."],
     "AsyncPanel discriminated union",
     [("Flags", "3 booleans", "1 discriminant", "Discriminant")],
     ["Zod infer union?", "React Query typed error?"],
     "memory-map-master.md"),

    (32, "generic-react-components", "Generic React Components in TypeScript",
     "Shopify, GitHub, Microsoft", "Hard",
     "Props<T> with constraints; forwardRef generics",
     "Reusable typed components",
     [("props: any", "Unsafe"), ("Generic <T>", "Reusable DataTable<T>"), ("Duplicate per type", "Verbose")],
     "Generic with extends constraint",
     ["interface DataTableProps<T extends {id:string}>.", "forwardRef generic syntax tricky — use typed wrapper.", "ComponentPropsWithoutRef utility."],
     "DataTable<T> column defs",
     [("Typing", "any", "Generic T", "Generic")],
     ["Generic custom hooks?", "Type inference from props?"],
     "memory-map-master.md"),

    (33, "accessibility-react-patterns", "Accessibility Patterns in React",
     "Apple, Microsoft, GOV.UK", "Hard",
     "Semantic HTML first; ARIA when needed; keyboard",
     "a11y senior signal",
     [("div onClick", "Bad"), ("button", "Good"), ("ARIA everything", "Overkill")],
     "Semantic + keyboard + focus management",
     ["Label linked with htmlFor/useId.", "Keyboard operable interactive elements.", "aria-live for dynamic updates.", "Focus visible styles.", "Test with axe and keyboard only."],
     "Accessible modal dialog",
     [("Custom widget", "div", "button + role if needed", "Native first")],
     ["Skip links?", "Live region politeness levels?"],
     "memory-map-master.md"),

    (34, "xss-dangerouslysetinnerhtml", "XSS and dangerouslySetInnerHTML",
     "Auth0, Okta, OpenAI", "Hard",
     "Sanitize HTML; prefer markdown pipeline",
     "Security in rich text UI",
     [("Raw HTML from LLM", "XSS risk"), ("DOMPurify sanitize", "Safer"), ("Plain text only", "Safest")],
     "Sanitize + CSP + avoid inline scripts",
     ["LLM output can contain script tags.", "Use DOMPurify or rehype-sanitize.", "Content-Security-Policy header.", "Never pass user HTML unsanitized.", "Markdown safer than raw HTML."],
     "sanitize(html) before render",
     [("Render", "dangerouslySetInnerHTML raw", "sanitized", "sanitized")],
     ["Markdown vs HTML LLM?", "CSP nonce with Next?"],
     "memory-map-master.md"),

    (35, "auth-protected-routes-react", "Protected Routes and Auth State",
     "Auth0, Stripe, Plaid", "Medium",
     "AuthProvider + redirect; token refresh",
     "Authentication UI flow",
     [("Check token in each component", "Duplicate"), ("ProtectedRoute wrapper", "Central"), ("Middleware Next.js", "Server gate")],
     "Context or Query for session + route guard",
     ["Load session on app init.", "Show skeleton while validating.", "Redirect unauthenticated to login.", "Preserve return URL.", "Refresh token silent before expiry."],
     "ProtectedRoute outlet redirect",
     [("Storage", "localStorage only", "httpOnly cookie + API", "httpOnly cookie")],
     ["RBAC UI gating?", "SSR auth check?"],
     "memory-map-master.md"),

    (36, "design-system-architecture", "Design System Architecture in React",
     "Shopify Polaris, Atlassian, IBM", "Hard",
     "Tokens + primitives + patterns; headless optional",
     "Component library structure",
     [("Copy-paste components", "Drift"), ("Design tokens + Storybook", "Scale"), ("Monolith UI folder", "Chaos")],
     "Tokens → primitives → composites → docs",
     ["CSS variables or Tailwind theme for tokens.", "Variant API via cva or similar.", "Storybook for docs and visual test.", "Semver independent package.", "Composition with Radix primitives."],
     "Button variants token-driven",
     [("Styling", "Inline styles", "Token system", "Tokens")],
     ["Theming dark mode?", "Tree-shaking exports?"],
     "component-patterns.md"),

    (37, "micro-frontends-react", "Micro Frontends in React",
     "Spotify, IKEA, Zalando", "Hard",
     "Module federation or iframe; shared design system",
     "Large org frontend scale",
     [("Monolith SPA", "Simple"), ("Module Federation", "Runtime integrate"), ("Iframe MFE", "Isolation heavy")],
     "Federation for team autonomy with shared shell",
     ["Shell app handles routing/auth.", "Remote exposes exposed modules.", "Shared react singleton version.", "Independent deploy.", "Tradeoff: runtime coupling vs build complexity."],
     "Webpack ModuleFederation config sketch",
     [("Integration", "Monorepo only", "Federation", "Team scale dependent")],
     ["Single-spa?", "CSS isolation?"],
     "memory-map-master.md"),

    (38, "state-management-redux-zustand", "Redux Toolkit vs Zustand",
     "Coinbase, Reddit, Discord", "Medium",
     "Redux for middleware/debug; Zustand for simplicity",
     "Global client state pick",
     [("Redux Toolkit", "Large app tooling"), ("Zustand", "Minimal API"), ("Context only", "Perf limits")],
     "Zustand default; Redux if time-travel/middleware required",
     ["RTK Query overlaps server cache.", "Zustand selectors prevent re-render.", "Redux DevTools.", "Don't put server cache in either — use Query."],
     "Zustand cart store slice",
     [("Boilerplate", "Redux verbose", "Zustand minimal", "Zustand for MVP")],
     ["Jotai vs Zustand?", "When Redux still wins?"],
     "state-management.md"),

    (39, "react-18-concurrent-features", "React 18 Concurrent Features",
     "Meta, Vercel, Shopify", "Hard",
     "Transitions defer non-urgent updates",
     "Concurrent UX",
     [("Sync setState filter", "Input lag"), ("startTransition", "Smooth"), ("debounce only", "Partial")],
     "startTransition + useDeferredValue",
     ["Mark heavy filter as transition.", "UI stays responsive.", "useDeferredValue for deferred display.", "Suspense for lazy/data.", "Automatic batching in 18."],
     "Search filter startTransition",
     [("Priority", "All sync", "Transition", "Transition")],
     ["useOptimistic React 19?", "Suspense boundaries nesting?"],
     "rendering-reconciliation.md"),

    (40, "strict-mode-double-mount", "React Strict Mode Double Mounting",
     "Meta, Google, Microsoft", "Medium",
     "Dev-only double invoke to find missing cleanup",
     "Development behavior",
     [("Remove StrictMode", "Hides bugs"), ("Fix effect cleanup", "Correct"), ("Ignore duplicate fetch", "Bad prod risk")],
     "Idempotent effects with cleanup",
     ["useEffect runs mount-unmount-remount in dev.", "Missing cleanup → duplicate subscriptions.", "AbortController prevents duplicate fetch.", "Not a production behavior."],
     "Fetch with abort on cleanup",
     [("Dev UX", "Disable Strict", "Proper cleanup", "Cleanup")],
     ["Production double fetch?", "React 19 Strict changes?"],
     "hooks-deep-dive.md"),

    (41, "css-in-js-vs-tailwind-react", "CSS-in-JS vs Tailwind in React",
     "Vercel, Netflix, Stripe", "Medium",
     "Tailwind for utility speed; CSS modules for isolation",
     "Styling architecture",
     [("Inline styles", "No pseudo"), ("Tailwind", "Rapid UI"), ("Styled-components", "Runtime cost RSC issue")],
     "Tailwind or CSS modules for RSC apps",
     ["RSC pushes away runtime CSS-in-JS.", "Tailwind + design tokens.", "CSS modules scoped.", "Variant libraries cva."],
     "Button with cva variants",
     [("RSC", "styled-components default", "Tailwind/CSS modules", "Zero runtime CSS")],
     ["Panda CSS?", "Dark mode strategy?"],
     "memory-map-master.md"),

    (42, "event-delegation-react", "Synthetic Events and Delegation",
     "Meta, Google, Microsoft", "Medium",
     "React pools events; attach at root in legacy",
     "Event system",
     [("Native addEventListener each node", "Verbose"), ("React onClick", "Synthetic wrapper"), ("Delegation pattern", "List performance")],
     "React 17+ delegates to root on container",
     ["e.stopPropagation still works.", "passive events for scroll perf.", "onClick on parent for dynamic child lists — careful with target check."],
     "List item click delegation",
     [("Handler", "Inline lambda every row", "Stable callback", "Stable")],
     ["React 17 event delegation change?", "preventDefault passive?"],
     "memory-map-master.md"),

    (43, "code-splitting-strategies", "Code Splitting Strategies",
     "Amazon, Google, Airbnb", "Medium",
     "Route split first; component split for heavy libs",
     "Bundle optimization",
     [("Single bundle", "Slow FCP"), ("Route lazy", "Standard"), ("Component lazy", "Heavy chart/editor")],
     "Route-level lazy + prefetch on hover",
     ["Analyze bundle visualizer.", "Split admin dashboard separately.", "Prefetch link hover import().", "Suspense fallback skeleton."],
     "lazy AdminDashboard",
     [("Granularity", "Every component", "Routes + heavy", "Balanced")],
     ["Preload on intent?", "SSR lazy chunks?"],
     "performance-optimization.md"),

    (44, "react-query-cache-invalidation", "Cache Invalidation Strategies",
     "Stripe, Supabase, PlanetScale", "Hard",
     "Invalidate queries on mutation; granular keys",
     "Cache coherence",
     [("Refetch everything", "Wasteful"), ("Targeted invalidate", "Efficient"), ("Manual setQueryData", "Optimistic")],
     "Hierarchical query keys + invalidate prefixes",
     ["['posts'] and ['posts', id] hierarchy.", "invalidateQueries({queryKey:['posts']}).", "setQueryData for single entity update.", "staleTime tuning per entity type."],
     "invalidate after createPost",
     [("Update", "Refetch all", "setQueryData + invalidate", "Hybrid")],
     ["Optimistic vs invalidate?", "Real-time invalidate via WS?"],
     "data-fetching-caching.md"),

    (45, "render-props-vs-hooks", "Render Props vs Hooks",
     "React community, Airbnb legacy", "Medium",
     "Hooks replaced most render prop patterns",
     "API evolution",
     [("Render prop <Data fn={} />", "Callback nesting"), ("useData hook", "Clean"), ("Both mixed", "Confusing")],
     "Hooks for new code",
     ["Render props still valid for inversion.", "Hooks easier to compose.", "No wrapper component nesting.", "Libraries migrated Mouse/useMouse."],
     "useMouse vs Mouse render prop",
     [("New code", "Render props", "Hooks", "Hooks")],
     ["When render props still better?", "Children as function?"],
     "component-patterns.md"),

    (46, "iframe-integration-react", "Integrating Third-Party Widgets (iframe)",
     "Stripe Checkout, Intercom, Plaid", "Medium",
     "postMessage bridge; sandbox attrs",
     "Safe embedding",
     [("eval script", "Unsafe"), ("iframe sandbox", "Isolated"), ("npm package", "Preferred if available")],
     "Official SDK or sandboxed iframe",
     ["Listen message event for height/payment done.", "Validate event.origin.", "React wrapper component lifecycle.", "Cleanup listener on unmount."],
     "Stripe Embedded Checkout wrapper",
     [("Security", "inline script", "iframe + origin check", "iframe")],
     ["OAuth popup pattern?", "CSP frame-ancestors?"],
     "memory-map-master.md"),

    (47, "drag-and-drop-react", "Drag and Drop in React",
     "Trello, Notion, Figma", "Hard",
     "dnd-kit or react-beautiful-dnd; keyboard a11y",
     "DnD UX",
     [("HTML5 DnD alone", "Limited mobile"), ("dnd-kit", "Modern a11y"), ("Manual mouse events", "Reinvent")],
     "dnd-kit with sortable context",
     ["Sensors for pointer and keyboard.", "Optimistic reorder local state.", "Persist order API on drop.", "Touch support."],
     "SortableList dnd-kit",
     [("Library", "react-beautiful-dnd unmaintained", "dnd-kit", "dnd-kit")],
     ["Virtual list + DnD?", "Multi-list drag?"],
     "memory-map-master.md"),

    (48, "internationalization-react", "i18n in React (react-i18next)",
     "Airbnb, Booking.com, Uber", "Medium",
     "Keys not concatenated strings; locale date/number",
     "Internationalization",
     [("Hard-coded English", "Bad"), ("react-i18next", "Standard"), ("Google translate widget", "Poor UX")],
     "i18next + namespace lazy load",
     ["t('checkout.title') keys.", "Interpolation {{name}}.", "Format dates with Intl.", "RTL layout CSS.", "Suspense load language bundle."],
     "useTranslation checkout namespace",
     [("Strings", "Inline", "Key files", "Key files")],
     ["Plural rules?", "SSR locale detection?"],
     "memory-map-master.md"),

    (49, "feature-flags-react-ui", "Feature Flags in React UI",
     "LaunchDarkly, Netflix, GitHub", "Medium",
     "Flag provider; skeleton while loading flags",
     "Gradual rollout UI",
     [("if (env) hardcode", "Not dynamic"), ("LaunchDarkly SDK", "Runtime"), ("Build-time only", "No runtime toggle")],
     "Flag provider + hook useFlag('new-chat')",
     ["Load flags on init.", "Fallback default false.", "Don't flash wrong UI — wait or skeleton.", "Analytics track flag exposure."],
     "useFeatureFlag newDashboard",
     [("Source", "Env var only", "Flag service", "Flag service")],
     ["A/B assignment persist?", "SSR flags?"],
     "memory-map-master.md"),

    (50, "performance-lighthouse-react", "Core Web Vitals in React SPAs",
     "Google, Shopify, Web.dev", "Hard",
     "LCP FID INP — code split, images, defer JS",
     "Performance metrics",
     [("Ignore metrics", "SEO/UX hit"), ("Optimize LCP image", "Hero priority"), ("Hydration cost", "RSC/SSR helps")],
     "Measure → LCP element → split → lazy",
     ["LCP: optimize hero image priority fetchpriority.", "INP: break long tasks transitions.", "CLS: reserve image dimensions.", "SSR/SSG for marketing pages."],
     "img fetchPriority high LCP",
     [("Rendering", "CSR only marketing", "SSR/SSG", "SSR/SSG")],
     ["Partial hydration?", "Streaming SSR metrics?"],
     "performance-optimization.md"),

    (51, "react-native-vs-react-web", "React vs React Native (Interview Bridge)",
     "Meta, Expo, Discord", "Medium",
     "Same React model; different primitives View Text",
     "Cross-platform mental model",
     [("DOM elements web", "div span"), ("Native components", "View Text"), ("Shared logic hooks", "Reuse business hooks")],
     "Share hooks; platform-specific UI",
     ["useState/useEffect same.", "StyleSheet vs CSS.", "Navigation React Navigation.", "Don't assume DOM APIs on native."],
     "Shared useAuth hook",
     [("UI", "Same components", "Platform split", "Platform split")],
     ["Expo router?", "Native performance lists?"],
     "memory-map-master.md"),

    (52, "storybook-component-development", "Storybook for Component Development",
     "Chromatic, Shopify, Storybook", "Medium",
     "Stories as living docs; interaction tests",
     "Component workflow",
     [("Dev in app only", "Slow feedback"), ("Storybook isolated", "Fast iterate"), ("No visual test", "Regressions")],
     "Storybook + MSW + visual regression",
     ["Default and edge state stories.", "Controls for props.", "Interaction tests play function.", "Chromatic CI diff."],
     "Button story variants",
     [("Testing", "App only", "Storybook + Chromatic", "Combined")],
     ["Composition stories?", "Accessibility addon?"],
     "component-patterns.md"),

    (53, "eslint-react-hooks-rules", "ESLint react-hooks Rules",
     "Meta, Open source teams", "Easy",
     "exhaustive-deps catches stale bugs",
     "Static analysis",
     [("Disable rules", "Ship bugs"), ("Fix deps/cleanup", "Correct"), ("eslint-disable line", "Last resort")],
     "Follow exhaustive-deps; extract functions",
     ["Rules of hooks enforced.", "Missing deps warning.", "Extract stable callback or useCallback when needed.", "Custom eslint for design system."],
     "Fix deps warning refactor",
     [("Deps", "Ignore", "Fix root", "Fix")],
     ["React Compiler make deps moot?", "Custom hook deps?"],
     "hooks-deep-dive.md"),

    (54, "batching-automatic-react-18", "Automatic Batching in React 18",
     "Meta, React team", "Medium",
     "Multiple setStates → one re-render in async too",
     "Update batching",
     [("React 17 async double render", "Old behavior"), ("React 18 auto batch", "Default"), ("flushSync escape hatch", "Rare")],
     "Default batch; flushSync only when must sync DOM",
     ["Event handlers always batched.", "setTimeout/promise batched in 18.", "flushSync forces sync for third-party lib.", "Fewer intermediate paints."],
     "Three setStates one paint",
     [("Sync need", "Always flushSync", "Rare flushSync", "Rare")],
     ["React 19 batch changes?", "Batching with transitions?"],
     "rendering-reconciliation.md"),

    (55, "server-state-offline-react", "Offline-First UI Patterns",
     "Notion, Figma, Linear", "Hard",
     "Optimistic queue; online detector; sync status",
     "Offline UX",
     [("Block UI offline", "Poor UX"), ("Queue mutations", "Better"), ("Full PWA sync", "Complex")],
     "Online banner + queued mutations replay",
     ["navigator.onLine + events.", "Persist queue IndexedDB.", "Replay on reconnect.", "Conflict UI if server rejects."],
     "useOnlineStatus hook",
     [("Storage", "memory queue", "IndexedDB", "IndexedDB")],
     ["CRDT vs last-write?", "Service worker cache?"],
     "data-fetching-caching.md"),

    (56, "react-table-large-datasets", "Build a Data Table with Sort/Filter",
     "Bloomberg, Stripe Dashboard, AWS", "Hard",
     "TanStack Table headless + virtualized rows",
     "Complex table UI",
     [("HTML table only", "No scale"), ("TanStack Table", "Headless logic"), ("AG Grid", "Heavy full solution")],
     "TanStack Table + Virtual",
     ["Column defs with accessorFn.", "Client vs server sort/filter.", "Virtualize tbody.", "Sticky header CSS.", "Selection state lifted."],
     "DataTable sort filter virtual",
     [("Logic", "Roll own sort", "TanStack Table", "TanStack Table")],
     ["Server-side pagination?", "Column resize persist?"],
     "performance-optimization.md"),

    (57, "theme-dark-mode-react", "Dark Mode Implementation",
     "GitHub, Twitter, Slack", "Medium",
     "CSS variables + class on html; avoid flash",
     "Theming",
     [("Inline theme state only", "Flash"), ("class dark on html", "Standard"), ("Separate CSS files", "Maintain burden")],
     "ThemeProvider + localStorage + system pref",
     ["Match media prefers-color-scheme.", "Persist user override.", "Script in head prevent flash FOUC.", "Context toggles theme."],
     "ThemeProvider useEffect flash script",
     [("Storage", "None", "localStorage + system", "Both")],
     ["Tailwind dark:", "Per-component tokens?"],
     "state-management.md"),

    (58, "react-query-suspense", "TanStack Query with Suspense",
     "Remix, React 19 apps", "Hard",
     "useSuspenseQuery throws promise to boundary",
     "Suspense data loading",
     [("isLoading branches", "Verbose"), ("Suspense boundary", "Declarative"), ("use + promise", "React 19")],
     "Suspense boundary per route segment",
     ["useSuspenseQuery no isLoading.", "Error boundary sibling.", "Streaming SSR compatible patterns.", "Waterfall risk — prefetch parallel."],
     "Suspense UserProfile query",
     [("Loading UI", "if loading", "Suspense fallback", "Suspense")],
     ["Error boundary pairing?", "Parallel suspense queries?"],
     "data-fetching-caching.md"),

    (59, "composition-slot-pattern", "Children and Slot Composition",
     "Radix, shadcn/ui, Vercel", "Medium",
     "children prop as composition slot",
     "Flexible layout API",
     [("title prop string only", "Limited"), ("children + header slot", "Flexible"), ("12 layout props", "Prop hell")],
     "children + optional named slots via props",
     ["Card accepts children body.", "Optional header/footer props as ReactNode.", "Compound alternative.", "shadcn pattern cloneable components."],
     "Card header={} children",
     [("API", "Props", "Composition", "Composition")],
     ["React 19 ref as prop?", "Slot component pattern?"],
     "component-patterns.md"),

    (60, "senior-react-system-design-prompt", "System Design: Build a Notion-like Editor UI",
     "Notion, Coda, Linear", "Hard",
     "Block model; lazy blocks; collaboration cursor",
     "Frontend system design",
     [("contentEditable alone", "Fragile"), ("ProseMirror/Slate", "Battle-tested"), ("Custom from scratch", "High cost")],
     "Block-based editor library + virtualize",
     ["Block array state normalized by id.", "Plugin architecture bold/link.", "Lazy load heavy blocks.", "OT/CRDT for collab — separate service.", "Undo stack command pattern."],
     "BlockEditor component architecture",
     [("Collab", "Lock file", "CRDT layer", "CRDT"), ("State", "One string", "Block map", "Block map")],
     ["How scale 10k blocks?", "Mobile editor UX?"],
     "component-patterns.md"),
]

GENAI_QUESTIONS = [
    (1, "build-streaming-chat-ui", "Build a Streaming ChatGPT-like UI",
     "OpenAI, Anthropic, Character.AI, Meta AI", "Hard",
     "SSE/fetch stream + message state + Stop",
     "End-to-end GenAI chat shell",
     [("Poll for response", "Bad latency"), ("SSE/fetch stream", "Standard"), ("WebSocket", "Bi-directional")],
     "fetch ReadableStream + AbortController",
     ["Clarify: multi-turn? file upload? model select?", "State: messages array with status enum.", "Optimistic user bubble.", "Stream append assistant content.", "Stop aborts fetch.", "Markdown render sanitized.", "aria-live for new tokens."],
     "ChatLayout MessageList ChatInput useChatStream",
     [("Transport", "Polling", "SSE/stream", "Stream"), ("Stop", "Ignore", "AbortController", "Abort")],
     ["How handle reconnect?", "Rate limit UI?", "Thread persistence?"],
     "streaming-sse-chat-ui.md"),

    (2, "stop-generation-abortcontroller", "Implement Stop Generation Button",
     "OpenAI, Google Gemini, Copilot", "Medium",
     "AbortController.abort() on active fetch",
     "Stream cancellation UX",
     [("Ignore stop", "Waste cost"), ("AbortController", "Correct"), ("Close tab only", "Bad UX")],
     "Shared abort ref per stream",
     ["Store AbortController in ref.", "stop() calls abort.", "Catch AbortError silently.", "UI shows partial + Stopped.", "Cleanup abort on unmount."],
     "stop() abortRef.current.abort()",
     [("Error", "Show error toast", "Treat abort as normal", "Normal abort")],
     ["Abort mid-token?", "Server must handle disconnect?"],
     "streaming-sse-chat-ui.md"),

    (3, "markdown-render-llm-sanitize", "Safely Render LLM Markdown Output",
     "OpenAI, Notion AI, GitHub Copilot", "Hard",
     "react-markdown + rehype-sanitize — no raw HTML",
     "XSS-safe rich text from model",
     [("dangerouslySetInnerHTML", "XSS"), ("react-markdown + sanitize", "Pick"), ("Plain text only", "Safe limited")],
     "react-markdown + rehype-sanitize",
     ["Models emit markdown not trusted HTML.", "Syntax highlight code blocks.", "Copy code button.", "Links open new tab rel noopener.", "Sanitize strips script/onclick."],
     "ReactMarkdown remarkPlugins rehypeSanitize",
     [("HTML", "Raw", "Sanitized pipeline", "Sanitized")],
     ["KaTeX math?", "Mermaid diagrams sandbox?"],
     "rag-ui-patterns.md"),

    (4, "rag-citation-source-panel", "RAG UI with Citations and Source Panel",
     "Perplexity, Glean, Harvey", "Hard",
     "Citation chips + drawer with snippet",
     "Trust UX for enterprise RAG",
     [("Answer only", "No trust"), ("Inline citations + panel", "Enterprise"), ("Footnotes only", "Academic")],
     "CitationChip + SourceDrawer",
     ["Message metadata citations array.", "Click [1] opens drawer.", "Empty sources → no answer state.", "Highlight matching snippet.", "Loading retrieval indicator."],
     "AssistantMessage citations prop",
     [("Empty retrieval", "Hallucinate", "Refuse UI", "Refuse")],
     ["PDF page highlight?", "Citation hover preview?"],
     "rag-ui-patterns.md"),

    (5, "document-upload-ingest-status", "Document Upload with Ingestion Status",
     "Notion AI, Databricks, Anthropic", "Hard",
     "Upload → job id → poll/SSE status → ready",
     "Async RAG ingest UX",
     [("Instant query after upload", "Wrong"), ("Progress per doc", "Correct"), ("Block whole app", "Bad UX")],
     "UploadZone + per-file status row",
     ["Multipart upload to S3 presigned.", "Poll ingest job or SSE events.", "States: uploading parsing embedding ready error.", "Enable chat when doc ready.", "Cancel upload abort."],
     "DocumentRow status enum",
     [("Feedback", "Spinner only", "Per-stage progress", "Per-stage")],
     ["Batch upload 50 PDFs?", "Retry failed ingest?"],
     "rag-ui-patterns.md"),

    (6, "conversation-thread-history", "Conversation Thread History Sidebar",
     "ChatGPT, Claude, Slack AI", "Medium",
     "Thread list + URL threadId + Query cache",
     "Multi-chat persistence UI",
     [("Single thread only", "MVP"), ("Sidebar threads + URL", "Product"), ("LocalStorage only", "No sync")],
     "TanStack Query threads + router param",
     ["GET /threads list.", "Select sets route /chat/:id.", "New chat mutation.", "Rename/delete thread.", "Optimistic new thread."],
     "ThreadSidebar useQuery threads",
     [("Persist", "Memory", "API + URL", "API + URL")],
     ["Search threads?", "Archive vs delete?"],
     "00-genai-react-framework.md"),

    (7, "model-selector-cost-latency", "Model Selector with Cost/Latency Hints",
     "OpenAI, Azure OpenAI, Groq", "Medium",
     "Dropdown models + tooltip cost/latency",
     "Model routing UX",
     [("Hidden model", "No user control"), ("Selector with hints", "Transparent"), ("Raw model string", "Confusing")],
     "ModelPicker component + settings persist",
     ["models config from API.", "Show $/1M tokens estimate.", "Latency tier badge.", "Disable unavailable models.", "Persist choice localStorage."],
     "ModelSelect options hint",
     [("Default", "Most expensive", "Balanced default", "Balanced")],
     ["Org policy lock model?", "A/B test models?"],
     "memory-map-genai-react.md"),

    (8, "token-budget-context-warning", "Token Budget & Context Window Warning",
     "OpenAI, Anthropic, Cursor", "Hard",
     "Progress bar tokens used; warn truncate",
     "Context limit UX",
     [("Silent truncate", "Confusing"), ("Visible token meter", "Transparent"), ("Hard block send", "Strict")],
     "TokenMeter + warn at 80%",
     ["Estimate tokens client-side approx.", "Show remaining context.", "Suggest start new thread.", "Summarize old messages action.", "API returns context_length_exceeded."],
     "TokenBudgetBar used max",
     [("Over limit", "Fail mysteriously", "Warn + actions", "Warn")],
     ["Accurate token count API?", "Auto-summarize thread?"],
     "memory-map-genai-react.md"),

    (9, "optimistic-user-message-chat", "Optimistic User Message in Chat",
     "WhatsApp, ChatGPT, Slack", "Medium",
     "Instant user bubble; rollback on fail",
     "Chat send UX",
     [("Wait server echo", "Laggy"), ("Optimistic append", "Snappy"), ("No error handle", "Bad")],
     "Append user msg sending → sent/error",
     ["Generate client temp id.", "Status sending until ACK.", "On error mark failed + retry.", "Dedupe on server id return.", "Disable input while sending optional."],
     "addMessage optimistic status",
     [("Failure", "Disappear", "Show retry", "Retry")],
     ["Ordering with stream?", "Offline queue?"],
     "streaming-sse-chat-ui.md"),

    (10, "rate-limit-error-ui-llm", "Rate Limit & Quota Error UI",
     "OpenAI, Stripe AI, Vercel AI", "Medium",
     "429 UI with retry-after countdown",
     "API limit UX",
     [("Generic error", "Unhelpful"), ("429 specific UI", "Actionable"), ("Silent fail", "Bad")],
     "RateLimitBanner retryAfter",
     ["Parse Retry-After header.", "Countdown timer.", "Upgrade CTA if quota.", "Disable send until window.", "Log for support."],
     "if status===429 show banner",
     [("Retry", "Immediate spam", "Wait Retry-After", "Wait")],
     ["Tier upgrade flow?", "Per-user vs org quota?"],
     "memory-map-genai-react.md"),

    (11, "multimodal-image-attachment-ui", "Multimodal Image Attachment UI",
     "GPT-4V, Gemini, Claude Vision", "Hard",
     "Preview thumbnail + base64/upload + vision API",
     "Image + text prompt UI",
     [("Text only", "Limited"), ("Attachment chip preview", "Multimodal"), ("Paste URL only", "Fragile")],
     "AttachmentPreview + presigned upload",
     ["Drag-drop images.", "Validate size/type.", "Upload then send URL to model.", "Remove attachment before send.", "Loading thumbnail state."],
     "ChatInput attachments array",
     [("Upload", "Base64 huge payload", "Presigned S3", "Presigned")],
     ["Multiple images?", "Progress on upload?"],
     "memory-map-genai-react.md"),

    (12, "prompt-template-picker-ui", "Prompt Template Picker UI",
     "LangChain, Jasper, Copy.ai", "Medium",
     "Template gallery inserts into input",
     "Prompt productivity UX",
     [("Blank input only", "Slow users"), ("Template variables form", "Guided"), ("Hard-coded strings", "Unmaintainable")],
     "TemplateGallery + variable modal",
     ["Fetch templates API.", "Insert with {{var}} substitution.", "Preview filled prompt.", "Save custom template.", "Categories/tags filter."],
     "PromptTemplateModal variables",
     [("Storage", "Component state", "API templates", "API")],
     ["Version templates?", "Team shared templates?"],
     "00-genai-react-framework.md"),

    (13, "feedback-thumbs-evaluation-ui", "Thumbs Up/Down Feedback for LLM Responses",
     "OpenAI, Anthropic, Google", "Medium",
     "Feedback mutation + optional comment modal",
     "Human eval signal collection",
     [("No feedback", "Lost signal"), ("Thumbs + trace id", "ML ops"), ("Feedback spam", "Needs debounce")],
     "FeedbackButtons messageId traceId",
     ["POST /feedback with message id.", "Disable after submit.", "Optional comment.", "Analytics event.", "Don't block chat on fail."],
     "submitFeedback mutation",
     [("Identity", "Anonymous ok", "User id logged", "Logged")],
     ["A/B prompt eval?", "Export feedback dataset?"],
     "00-genai-react-framework.md"),

    (14, "side-by-side-model-compare", "Side-by-Side Model Comparison UI",
     "OpenAI Playground, Anthropic Workbench", "Hard",
     "Same prompt → two parallel streams",
     "Eval/compare UX",
     [("Sequential compare", "Slow"), ("Parallel streams", "Fast"), ("Single panel", "No compare")],
     "DualPane stream hooks",
     ["Two AbortControllers.", "Sync scroll optional.", "Show latency per model.", "Cost estimate each.", "Export comparison."],
     "CompareView modelA modelB",
     [("Stream", "Sequential", "Parallel", "Parallel")],
     ["Sync scroll?", "Blind compare mode?"],
     "memory-map-genai-react.md"),

    (15, "inline-copilot-ghost-text", "Inline Copilot Ghost Text Suggestion",
     "GitHub Copilot, Cursor, Superhuman", "Hard",
     "Ghost completion Tab to accept Esc dismiss",
     "Inline AI assist UX",
     [("Modal only", "Disruptive"), ("Inline ghost text", "Copilot pattern"), ("Auto-insert all", "Dangerous")],
     "GhostText debounced inline API",
     ["Debounce keystroke 300ms.", "Fetch completion.", "Show gray ghost suffix.", "Tab accepts Esc clears.", "Don't flash on fast typists."],
     "useInlineCompletion editor",
     [("Accept", "Auto apply", "Explicit Tab", "Tab")],
     ["Multi-line ghost?", "Privacy send code snippet?"],
     "memory-map-genai-react.md"),

    (16, "agent-tool-call-ui", "Display Agent Tool Calls in UI",
     "OpenAI Assistants, Anthropic, LangGraph", "Hard",
     "Expandable tool steps running/done/error",
     "Agent transparency UX",
     [("Hide tools", "Black box"), ("Step timeline", "Trust"), ("Raw JSON", "Dev only")],
     "ToolCallStep accordion status",
     ["Parse tool_call events from stream.", "Show name + args summary.", "Spinner running checkmark done.", "Error retry step.", "Collapse verbose args."],
     "ToolRunTimeline events",
     [("Detail", "Full JSON default", "Human summary", "Summary")],
     ["Human approve tool?", "Parallel tool calls?"],
     "00-genai-react-framework.md"),

    (17, "structured-json-streaming-ui", "Streaming Structured JSON (UI Schema)",
     "OpenAI JSON mode, Vercel AI SDK", "Hard",
     "Partial JSON parse or schema-validated chunks",
     "Structured output rendering",
     [("Wait full JSON", "Slow UX"), ("Incremental parse", "Progressive UI"), ("Regex extract", "Fragile")],
     "Schema form fills as JSON streams",
     ["Use zod schema.", "partial-json parser library.", "Show fields as validated.", "Error highlight invalid.", "Fallback raw view dev."],
     "useStructuredStream schema",
     [("Parse", "JSON.parse once", "Partial parser", "Partial")],
     ["UI forms from schema?", "Recover corrupt stream?"],
     "streaming-sse-chat-ui.md"),

    (18, "websocket-vs-sse-chat", "WebSocket vs SSE for Chat Apps",
     "Discord, Slack, OpenAI", "Hard",
     "SSE one-way stream; WS bi-directional",
     "Transport choice",
     [("SSE + REST send", "Simple"), ("WebSocket", "Real-time both ways"), ("Long polling", "Legacy")],
     "SSE stream + POST send for most LLM APIs",
     ["OpenAI pattern POST then stream response.", "WS if server pushes multiple event types.", "SSE auto-reconnect.", "Auth easier on POST fetch.", "WS for collaborative cursors."],
     "Architecture diagram POST+SSE vs WS",
     [("Chat LLM", "WS required", "SSE typical", "SSE"), ("Collab", "SSE enough", "WS", "WS")],
     ["GraphQL subscriptions?", "HTTP/3 streaming?"],
     "streaming-sse-chat-ui.md"),

    (19, "degraded-mode-llm-outage", "Degraded Mode When LLM API Is Down",
     "OpenAI, Enterprise SaaS", "Medium",
     "Cached answers + banner + retry queue",
     "Resilience UX",
     [("White screen error", "Bad"), ("Graceful banner + cached FAQ", "Enterprise"), ("Infinite spinner", "Bad")],
     "HealthCheck banner + fallback search",
     ["Probe /health model status.", "Show banner degraded.", "Offer cached docs search.", "Queue messages retry later.", "Status page link."],
     "DegradedBanner health query",
     [("UX", "Block app", "Partial features", "Partial")],
     ["Multi-region failover?", "Statuspage embed?"],
     "memory-map-genai-react.md"),

    (20, "accessible-ai-chat-live-region", "Accessible AI Chat (ARIA Live Regions)",
     "Microsoft, Apple, GOV.UK", "Hard",
     "role=log aria-live polite; focus management",
     "a11y for streaming chat",
     [("Silent stream", "SR users miss updates"), ("aria-live polite", "Correct"), ("aria-live assertive every token", "Too aggressive")],
     "polite live region + manual review button",
     ["New assistant message announced politely.", "Don't move focus on each token.", "Keyboard send Shift+Enter.", "Stop button focusable.", "High contrast mode support."],
     "div role=log aria-live=polite",
     [("Announce", "Every token assertive", "Message complete polite", "Polite")],
     ["VoiceOver test plan?", "Mobile a11y chat?"],
     "memory-map-genai-react.md"),
]
